"""Pack ChatGPT's layered world map (3840x2560 master + 11 land masks) for the game.

Usage: python3 tools/pack_worldmap.py /path/to/extracted/Lorebound-Layered-World-Map

Writes
  src/art/wm-base.webp        the whole painting at OUT_W wide (the layer under everything)
  src/art/wm-<id>.webp        one transparent layer per land, cut from the same downscaled painting
  src/worldmap_defs.js        WM_DEFS: size, per-land box (x,y,w,h), label point and a simplified SVG outline
The layers are cut from the *downscaled* master with a 2-px-dilated mask, so they line up with the base exactly
and no seam shows when a land is greyed out or lifted on hover.
"""
import sys, json, os
from PIL import Image, ImageFilter

SRC = sys.argv[1]
OUT_W = 2400
meta = json.load(open(os.path.join(SRC, 'metadata/regions.json')))
MW, MH = meta['width'], meta['height']
S = OUT_W / MW
OUT_H = round(MH * S)

master = Image.open(os.path.join(SRC, 'master/lorebound-3840.png')).convert('RGB')
small = master.resize((OUT_W, OUT_H), Image.LANCZOS)
small.save('src/art/wm-base.webp', 'WEBP', quality=78, method=6)
print('base', small.size, os.path.getsize('src/art/wm-base.webp') // 1024, 'KB')


def dp(pts, eps):
    """Douglas-Peucker on an open polyline."""
    if len(pts) < 3: return pts
    (x0, y0), (x1, y1) = pts[0], pts[-1]
    dx, dy = x1 - x0, y1 - y0; L = (dx * dx + dy * dy) ** 0.5 or 1e-9
    best, bi = -1, 0
    for i in range(1, len(pts) - 1):
        px, py = pts[i]
        d = abs(dy * px - dx * py + x1 * y0 - y1 * x0) / L if (dx or dy) else ((px - x0) ** 2 + (py - y0) ** 2) ** 0.5
        if d > best: best, bi = d, i
    if best <= eps: return [pts[0], pts[-1]]
    return dp(pts[:bi + 1], eps)[:-1] + dp(pts[bi:], eps)


def area(r):
    a = 0
    for i in range(len(r)):
        x0, y0 = r[i]; x1, y1 = r[(i + 1) % len(r)]; a += x0 * y1 - x1 * y0
    return abs(a) / 2


defs = {'w': OUT_W, 'h': OUT_H, 'order': meta['paintOrder'], 'regions': []}
for r in meta['regions']:
    rid = r['id']; fid = rid.lower()
    mask = Image.open(os.path.join(SRC, r['mask'])).convert('L').filter(ImageFilter.MaxFilter(5))  # dilate ~2 px
    m = mask.resize((OUT_W, OUT_H), Image.BILINEAR)
    layer = small.copy(); layer.putalpha(m)
    bb = m.getbbox(); x0, y0, x1, y1 = bb
    piece = layer.crop(bb)
    piece.save(f'src/art/wm-{fid}.webp', 'WEBP', quality=80, method=6)
    rings = []
    for ring in r['rings']:
        pts = [(x * S, y * S) for x, y in ring]
        if area(pts) < 40: continue           # specks: too small to hover anyway
        pts = dp(pts + [pts[0]], 1.2)[:-1]
        if len(pts) >= 3: rings.append(pts)
    path = ''.join('M' + 'L'.join('%.0f %.0f' % p for p in ring) + 'Z' for ring in rings)
    defs['regions'].append({'id': rid, 'name': r['name'], 'x': x0, 'y': y0, 'w': x1 - x0, 'h': y1 - y0,
                            'lx': round(r['label']['x'] * S), 'ly': round(r['label']['y'] * S), 'path': path})
    print(rid, piece.size, os.path.getsize(f'src/art/wm-{fid}.webp') // 1024, 'KB', len(rings), 'rings', len(path), 'chars')

open('src/worldmap_defs.js', 'w').write('/* generated by tools/pack_worldmap.py: layered world map geometry */\nvar WM_DEFS = ' + json.dumps(defs, separators=(',', ':')) + ';\n')
print('defs', os.path.getsize('src/worldmap_defs.js') // 1024, 'KB')
