"""Pack the HD sprite pack (ChatGPT 'fantasy starter pack') into two game sheets + a defs file.
   characters -> src/art/sheet-hd.png, props -> src/art/sheet-hdprops.png, defs -> src/hd_defs.js
   Usage: python3 tools/pack_hd.py <pack folder>"""
import json, sys, os
from PIL import Image
P = sys.argv[1]
CHAR_SCALE = 0.6        # packed pixels per source pixel
PROP_SCALE = 0.5
CHARS = [n for n in ['knight', 'wizard', 'skeleton', 'goblin', 'troll'] + sys.argv[2:] if os.path.exists(f'{P}/metadata/{n}.json')]
KNIGHT_H = 26.0         # logical height of the knight's idle frame in the world (one tile = 16)

def shelf(items, width):
    x = y = rowh = 0; out = []
    for key, im in items:
        if x + im.width > width: x = 0; y += rowh + 2; rowh = 0
        out.append((key, im, x, y)); x += im.width + 2; rowh = max(rowh, im.height)
    return out, y + rowh

defs = {'chars': {}, 'props': {}}
items = []
for n in CHARS:
    m = json.load(open(f'{P}/metadata/{n}.json')); sheet = Image.open(f'{P}/sheets/{n}.png').convert('RGBA')
    world = m.get('suggestedDisplayScale', 0.5) / 0.5 * KNIGHT_H / 222.0 / CHAR_SCALE   # logical px per packed px
    anims = {'idle': m['animations']['idle']['frames'], 'walk': m['animations']['walk']['frames'], 'death': m['animations']['death']['frames'][-1:]}
    fps = {'idle': m['animations']['idle']['fps'], 'walk': m['animations']['walk']['fps'], 'death': 1}
    defs['chars'][n] = {'scale': round(world, 5), 'anims': {}}
    for a, idxs in anims.items():
        for i in idxs:
            f = m['frames'][i]; r = f['rect']
            im = sheet.crop((r['x'], r['y'], r['x'] + r['w'], r['y'] + r['h']))
            im = im.resize((max(1, round(r['w'] * CHAR_SCALE)), max(1, round(r['h'] * CHAR_SCALE))), Image.LANCZOS)
            items.append(((n, a, i, f['anchor']['x'] * CHAR_SCALE, f['anchor']['y'] * CHAR_SCALE), im))
        defs['chars'][n]['anims'][a] = {'fps': fps[a], 'frames': []}
placed, h = shelf(items, 2048)
atlas = Image.new('RGBA', (2048, h), (0, 0, 0, 0))
for (n, a, i, ax, ay), im, x, y in placed:
    atlas.paste(im, (x, y)); defs['chars'][n]['anims'][a]['frames'].append([x, y, im.width, im.height, round(ax, 1), round(ay, 1)])
atlas.save('src/art/sheet-hd.webp', 'WEBP', quality=90, method=6)

pm = json.load(open(f'{P}/metadata/world_props.atlas.json')); ps = Image.open(f'{P}/sheets/world_props.png').convert('RGBA')
pitems = []
for k, v in pm['frames'].items():
    fr, sss, pv = v['frame'], v['spriteSourceSize'], v['pivot']
    im = ps.crop((fr['x'], fr['y'], fr['x'] + fr['w'], fr['y'] + fr['h'])).resize((round(fr['w'] * PROP_SCALE), round(fr['h'] * PROP_SCALE)), Image.LANCZOS)
    ax = (pv['x'] * v['sourceSize']['w'] - sss['x']) * PROP_SCALE; ay = (pv['y'] * v['sourceSize']['h'] - sss['y']) * PROP_SCALE
    pitems.append(((k, ax, ay), im))
placed, h = shelf(pitems, 1024)
patlas = Image.new('RGBA', (1024, h), (0, 0, 0, 0))
for (k, ax, ay), im, x, y in placed:
    patlas.paste(im, (x, y)); defs['props'][k] = [x, y, im.width, im.height, round(ax, 1), round(ay, 1)]
patlas.save('src/art/sheet-hdprops.webp', 'WEBP', quality=90, method=6)
defs['propScale'] = PROP_SCALE
open('src/hd_defs.js', 'w').write('/* HD painted sprites (generated by tools/pack_hd.py). frames: [x, y, w, h, anchorX, anchorY] in the packed sheet */\nvar HD_DEFS = ' + json.dumps(defs, separators=(',', ':')) + ';\n')
print('chars', atlas.size, os.path.getsize('src/art/sheet-hd.webp') // 1024, 'KB; props', patlas.size, os.path.getsize('src/art/sheet-hdprops.webp') // 1024, 'KB')
