"""Pack the per-creature painted sprite sheets (Lorebound Art Pack from ChatGPT/Codex) into small WebP sheets.
   Usage: python3 tools/pack_creatures.py <Lorebound-Art-Pack folder> [Hk] [Hmax] [quality]
   out: src/art/cr-<name>.webp (one per creature) + src/creature_defs.js
   Hk   = packed height (px) of a knight-sized body; Hmax caps big creatures and bosses (they are drawn upscaled)."""
import json, sys, os, io
from PIL import Image
P = sys.argv[1]; HK = float(sys.argv[2]) if len(sys.argv) > 2 else 100; HMAX = float(sys.argv[3]) if len(sys.argv) > 3 else 130; Q = int(sys.argv[4]) if len(sys.argv) > 4 else 78
KNIGHT_LOGICAL = 26.0     # logical (16-px-tile) height of a 0.5-scale body
REF_BODY = 221.0          # source height of the pack's 0.5-scale knight body
defs = {}; total = 0
for f in sorted(os.listdir(f'{P}/metadata')):
    m = json.load(open(f'{P}/metadata/{f}')); name = m['name']; sheet = Image.open(f"{P}/{m['sheet']}").convert('RGBA')
    sds = m.get('suggestedDisplayScale', 0.5)
    logical_per_src = KNIGHT_LOGICAL / REF_BODY * sds / 0.5
    crops = []
    for fr in m['frames']:
        r = fr['rect']; c = sheet.crop((r['x'], r['y'], r['x'] + r['w'], r['y'] + r['h']))
        bb = c.getchannel('A').point(lambda v: 255 if v > 6 else 0).getbbox() or (0, 0, 1, 1)
        crops.append((c.crop(bb), fr['anchor']['x'] - bb[0], fr['anchor']['y'] - bb[1]))
    body = max(c[0].height for c in crops[:6])
    s = min(HK / REF_BODY * sds / 0.5, HMAX / body)          # packed px per source px
    tiles = [(c.resize((max(1, round(c.width * s)), max(1, round(c.height * s))), Image.LANCZOS), ax * s, ay * s) for c, ax, ay in crops]
    # 6 columns x 4 rows (idle, walk, attack, death), each row as tall as its tallest frame
    colw = max(t[0].width for t in tiles); W = (colw + 2) * 6
    rowh = [max(t[0].height for t in tiles[r * 6:(r + 1) * 6]) for r in range(4)]
    H = sum(h + 2 for h in rowh); atlas = Image.new('RGBA', (W, H), (0, 0, 0, 0)); out = []; y = 0
    for r in range(4):
        for c in range(6):
            im, ax, ay = tiles[r * 6 + c]; x = c * (colw + 2); atlas.paste(im, (x, y)); out.append([x, y, im.width, im.height, round(ax, 1), round(ay, 1)])
        y += rowh[r] + 2
    b = io.BytesIO(); atlas.save(b, 'WEBP', quality=Q, alpha_quality=55, method=6); open(f'src/art/cr-{name}.webp', 'wb').write(b.getvalue()); total += len(b.getvalue())
    an = m['animations']
    defs[name] = {'scale': round(logical_per_src / s, 5), 'frames': out, 'anims': {k: {'frames': v['frames'], 'fps': v['fps'], 'loop': v.get('loop', True)} for k, v in an.items()}, 'label': m.get('label', name)}
    print(f'{name:12s} sds {sds:4} s {s:.3f} sheet {atlas.size} {len(b.getvalue()) // 1024} KB')
open('src/creature_defs.js', 'w').write('/* Painted creature sprites (generated by tools/pack_creatures.py). frames: [x, y, w, h, anchorX, anchorY]; scale = logical px per packed px */\nvar CREATURE_DEFS = ' + json.dumps(defs, separators=(',', ':')) + ';\n')
print('TOTAL', total // 1024, 'KB')
