"""Pack the one-shot defence / effect animations (Lorebound Knight Defence & Effects pack from ChatGPT) into WebP strips.
   Usage: python3 tools/pack_fx.py <lorebound-knight-defense-and-effects folder>
   out: src/art/cr-hero-knight-{1,2,3}-deflect.webp, cr-fx-ember.webp, cr-fx-shield.webp; merged into src/creature_defs.js
   The knights' parry frames share the hero sheets' scale exactly (frames 0 and 5 are the idle frame), so swapping
   sheets mid-fight does not jump. Uneven frame times are kept by repeating frames at 20 fps."""
import json, sys, io
from PIL import Image
P = sys.argv[1]; Q = 82
txt = open('src/creature_defs.js').read(); defs = json.loads(txt[txt.index('{'):txt.rindex('}') + 1])
LOG_PER_SRC = 26.0 / 221.0                      # logical px per source px for a 0.5-scale body (pack_creatures.py)

def seq(durs, fps=20):                           # frame indexes repeated to approximate per-frame durations
    out = []
    for i, d in enumerate(durs): out += [i] * max(1, round(d / (1000 / fps)))
    return out

def pack(name, meta_path, root, s, logical_per_src, anim, cell_anchor=None):
    m = json.load(open(meta_path)); sheet = Image.open(f"{root}/{m['sheet']}").convert('RGBA')
    tiles = []
    for fr in m['frames']:
        r = fr['rect']; c = sheet.crop((r['x'], r['y'], r['x'] + r['w'], r['y'] + r['h']))
        a = fr.get('anchor') or cell_anchor
        bb = c.getchannel('A').point(lambda v: 255 if v > 6 else 0).getbbox() or (0, 0, 1, 1)
        c = c.crop(bb); im = c.resize((max(1, round(c.width * s)), max(1, round(c.height * s))), Image.LANCZOS)
        tiles.append((im, (a['x'] - bb[0]) * s, (a['y'] - bb[1]) * s))
    W = sum(t[0].width + 2 for t in tiles); H = max(t[0].height for t in tiles)
    atlas = Image.new('RGBA', (W, H), (0, 0, 0, 0)); frames = []; x = 0
    for im, ax, ay in tiles: atlas.paste(im, (x, 0)); frames.append([x, 0, im.width, im.height, round(ax, 1), round(ay, 1)]); x += im.width + 2
    b = io.BytesIO(); atlas.save(b, 'WEBP', quality=Q, alpha_quality=70, method=6); open(f'src/art/cr-{name}.webp', 'wb').write(b.getvalue())
    durs = [fr['durationMs'] for fr in m['frames']]
    defs[name] = {'scale': round(logical_per_src / s, 5), 'frames': frames, 'anims': {anim: {'frames': seq(durs), 'fps': 20, 'loop': False}, 'idle': {'frames': [0], 'fps': 1, 'loop': True}}, 'label': m.get('label', name), 'fx': True}
    print(f'{name:24s} s {s:.3f} sheet {atlas.size} {len(b.getvalue()) // 1024} KB  {sum(durs)} ms')

for k in (1, 2, 3):
    hero = defs[f'hero-knight-{k}']; s = LOG_PER_SRC / hero['scale']          # the hero sheet's own packing scale
    pack(f'hero-knight-{k}-deflect', f'{P}/metadata/hero-knight-{k}-deflect.json', P, s, LOG_PER_SRC, 'deflect')
s_hero = LOG_PER_SRC / defs['hero-knight-1']['scale']
pack('fx-ember', f'{P}/metadata/ember-burst.json', P, s_hero, LOG_PER_SRC, 'burst')
pack('fx-shield', f'{P}/bone-shield/metadata/shield-shatter.json', f'{P}/bone-shield', 0.42, 17.0 / 362.0, 'shatter', {'x': 256, 'y': 256})  # the intact shield ~17 logical px across
open('src/creature_defs.js', 'w').write('/* Painted creature sprites (generated by tools/pack_creatures.py). frames: [x, y, w, h, anchorX, anchorY]; scale = logical px per packed px */\nvar CREATURE_DEFS = ' + json.dumps(defs, separators=(',', ':')) + ';\n')
