"""Pack the per-land painted terrain sets (Lorebound Art Pack) for the game.
   Usage: python3 tools/pack_terrain.py <Lorebound-Art-Pack folder>
   out: src/art/tr-l<N>.webp (24 painted 64-px tiles), src/art/tr-l<N>-props.webp (8 trimmed props), src/terrain_defs.js"""
import json, sys, io
from PIL import Image
P = sys.argv[1]; K = 4.0   # packed px per logical px for props
BIG = ('tree', 'willow', 'oak', 'pillar', 'menhir', 'spire', 'obelisk', 'arch', 'doorway', 'wall', 'battlement', 'outcrop', 'hull', 'mast', 'gate', 'stone ruin', 'standing stone', 'sarcophagus', 'stump', 'trunk')
SMALL = ('pile', 'urn', 'lantern', 'post', 'bollard', 'mushroom', 'vent', 'anchor', 'crate', 'kelp', 'reed', 'waypost', 'banner', 'gravestone', 'grave marker', 'fence', 'fern', 'brazier', 'stair', 'driftwood', 'log', 'hedge', 'briar', 'roots', 'boulder', 'lily')
FLAT = ('bone pile', 'skull', 'mushroom', 'reed', 'kelp', 'vent', 'slag', 'fern', 'lily', 'driftwood', 'roots')   # can sit on walkable ground
defs = {}
for n in range(1, 8):
    d = f'{P}/terrain/l{n}'; t = json.load(open(f'{d}/tiles-64.json')); tim = Image.open(f'{d}/tiles-64.png').convert('RGB')
    b = io.BytesIO(); tim.save(b, 'WEBP', quality=88, method=6); open(f'src/art/tr-l{n}.webp', 'wb').write(b.getvalue()); tsize = len(b.getvalue())
    frames = [[f['rect']['x'], f['rect']['y'], f['rect']['w'], f['rect']['h']] for f in t['frames']]
    pj = json.load(open(f'{d}/props.json')); pim = Image.open(f'{d}/props.png').convert('RGBA'); props = []; items = []
    for f in pj['frames']:
        r = f['rect']; c = pim.crop((r['x'], r['y'], r['x'] + r['w'], r['y'] + r['h'])); bb = c.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
        c = c.crop(bb); ax = f['anchor']['x'] - bb[0]; ay = min(f['anchor']['y'], bb[3]) - bb[1]
        lab = f.get('label', '').lower()
        size = 34 if any(w in lab for w in BIG) else 20 if any(w in lab for w in SMALL) else 26          # logical px of its longest side
        if 'lily' in lab: size = 22
        s = size * K / max(c.width, c.height); im = c.resize((max(1, round(c.width * s)), max(1, round(c.height * s))), Image.LANCZOS)
        items.append((im, ax * s, ay * s, lab, any(w in lab for w in FLAT), 'lily' in lab))
    W = sum(i[0].width + 2 for i in items); H = max(i[0].height for i in items); at = Image.new('RGBA', (W, H)); x = 0
    for im, ax, ay, lab, flat, water in items:
        at.paste(im, (x, 0)); props.append({'f': [x, 0, im.width, im.height, round(ax, 1), round(ay, 1)], 'label': lab, 'flat': flat, 'water': water}); x += im.width + 2
    b2 = io.BytesIO(); at.save(b2, 'WEBP', quality=82, alpha_quality=70, method=6); open(f'src/art/tr-l{n}-props.webp', 'wb').write(b2.getvalue())
    defs[f'L{n}'] = {'label': t['label'], 'tile': t['tileSize'], 'frames': frames, 'ground': t['groundVariants'], 'path': t['pathFrame'], 'liquid': t['liquidFrames'], 'liquidKind': t.get('liquidKind', 'water'), 'liquidFps': t['animations']['water']['fps'] if 'water' in t['animations'] else 4,
                     'edgeByMask': {int(k): v for k, v in t['edgeByMask'].items()}, 'propScale': 1 / K, 'props': props}
    print(f'L{n} {t["label"]}: tiles {tsize // 1024} KB, props {len(b2.getvalue()) // 1024} KB', [p['label'][:18] + ('*' if p['flat'] else '') for p in props])
open('src/terrain_defs.js', 'w').write('/* Painted terrain per land (generated by tools/pack_terrain.py). Tiles: 64-px frames drawn as one 16-px logical tile. Edges: edgeByMask[N=1|E=2|S=4|W=8]. Props: f = [x, y, w, h, anchorX, anchorY]. */\nvar TERRAIN_DEFS = ' + json.dumps(defs, separators=(',', ':')) + ';\n')
