/* ===================== LOREBOOK =====================
 * The five lost pages of each land. Every page is a scrap of the land's story stitched to a piece of real,
 * usable math for the creatures that live there. Pages are stored in the hero's Satchel once found. */
var LOREBOOK = {
  L1: [
    { title: 'The First Grave', lore: 'Before the fog there was a town here, and the town kept a ledger of its dead. The ledger counted in primes, because primes cannot be divided and neither, the gravediggers said, can the dead.',
      math: '<b>Prime factorisation</b> is the skeleton of a number. Divide by the smallest prime that works, then keep going: \\(360 = 2 \\cdot 180 = 2^2 \\cdot 90 = 2^3 \\cdot 45 = 2^3 \\cdot 3^2 \\cdot 5\\). A number is a <b>perfect square</b> when every exponent in its factorisation is even, and a <b>perfect cube</b> when every exponent is a multiple of 3. \\(360\\) is neither; \\(3600 = 2^4 \\cdot 3^2 \\cdot 5^2\\) is a square.' },
    { title: 'What the Rats Share', lore: 'The bone rats were not always many. One rat, cut by a careless shovel, became two, and the two shared everything: the same ribs, the same hunger. Whatever they share, the Gravedigger says, is the greatest of it that matters.',
      math: '<b>GCF</b> (greatest common factor): take the primes the numbers <i>share</i>, with the <i>smaller</i> exponent. <b>LCM</b> (least common multiple): take <i>every</i> prime that appears, with the <i>larger</i> exponent. For \\(24 = 2^3 \\cdot 3\\) and \\(36 = 2^2 \\cdot 3^2\\): \\(\\text{GCF} = 2^2 \\cdot 3 = 12\\) and \\(\\text{LCM} = 2^3 \\cdot 3^2 = 72\\). Check: \\(\\text{GCF} \\times \\text{LCM} = 24 \\times 36\\).' },
    { title: 'The Lich\'s Cube', lore: 'Vessarion keeps his life in a cube of marsh-iron buried under the eighth barrow. The cube\'s volume is written on the lid. The edge is not. He assumes nobody can take a root.',
      math: '<b>Roots undo powers.</b> \\(\\sqrt{n}\\) asks “what number squared gives \\(n\\)?”, \\(\\sqrt[3]{n}\\) asks “what number cubed?”. Use the prime factorisation: \\(\\sqrt[3]{1728} = \\sqrt[3]{2^6 \\cdot 3^3} = 2^2 \\cdot 3 = 12\\), because you take one third of every exponent. For a square root, halve the exponents: \\(\\sqrt{3600} = 2^2 \\cdot 3 \\cdot 5 = 60\\).' },
    { title: 'A Wisp Is Not Rational', lore: 'Follow a wisp and you will walk forever: its path never repeats and never ends. The townsfolk called such things irrational, and they were right, though not in the way they meant.',
      math: 'A <b>rational</b> number can be written as a fraction of integers, so its decimal ends or repeats: \\(\\tfrac{3}{8} = 0.375\\), \\(\\tfrac{2}{3} = 0.\\overline{6}\\). An <b>irrational</b> number cannot: \\(\\sqrt{2}\\), \\(\\sqrt[3]{10}\\), \\(\\pi\\). Quick test for a root: \\(\\sqrt{n}\\) is rational only when \\(n\\) is a perfect square (\\(\\sqrt{49} = 7\\)), \\(\\sqrt[3]{n}\\) only when \\(n\\) is a perfect cube. To <b>order</b> radicals, estimate: \\(\\sqrt{50}\\) sits just above \\(\\sqrt{49} = 7\\).' },
    { title: 'The Hollow Knight\'s Armour', lore: 'The knight\'s armour was forged entire, one piece of marsh-steel. Only later was it broken and mended with a number sewn outside and a number sewn in. Make it whole again and it falls apart.',
      math: '<b>Mixed ↔ entire radicals.</b> To simplify, pull out the largest perfect square (or cube) factor: \\(\\sqrt{72} = \\sqrt{36 \\cdot 2} = 6\\sqrt{2}\\); \\(\\sqrt[3]{54} = \\sqrt[3]{27 \\cdot 2} = 3\\sqrt[3]{2}\\). To go back to an entire radical, push the coefficient under the root as a power: \\(5\\sqrt{3} = \\sqrt{25 \\cdot 3} = \\sqrt{75}\\); \\(2\\sqrt[3]{7} = \\sqrt[3]{8 \\cdot 7} = \\sqrt[3]{56}\\).' }
  ],
  L2: [
    { title: 'The Forge-Born', lore: 'Nothing in the Peaks is born once. A cinder imp is born of a cinder imp, which is born of a cinder imp, and the mountain counts the generations as a small number written above a larger one.',
      math: '<b>Exponent laws</b> (same base): multiply → add exponents, \\(x^3 \\cdot x^5 = x^8\\); divide → subtract, \\(\\dfrac{x^7}{x^2} = x^5\\); power of a power → multiply, \\((x^3)^4 = x^{12}\\). A power of a product or quotient reaches every factor: \\((2x^2y)^3 = 8x^6y^3\\), \\(\\left(\\dfrac{a}{b}\\right)^2 = \\dfrac{a^2}{b^2}\\). The exponent only applies to what it touches: \\(-3^2 = -9\\) but \\((-3)^2 = 9\\).' },
    { title: 'Below the Fire-Line', lore: 'Dig under the lava and you find the mountain upside down: every chamber a mirror of the one above, every power turned on its head. The hounds hunt there by flipping.',
      math: '<b>Negative exponents</b> mean “flip it”: \\(x^{-n} = \\dfrac{1}{x^n}\\) and \\(\\dfrac{1}{x^{-n}} = x^n\\). So \\(2^{-3} = \\dfrac{1}{8}\\) and \\(\\left(\\dfrac{2}{3}\\right)^{-2} = \\left(\\dfrac{3}{2}\\right)^2 = \\dfrac{9}{4}\\). Anything (except 0) to the power 0 is 1: \\(7^0 = 1\\), \\((-5x)^0 = 1\\). Move a factor across the fraction bar by changing the sign of its exponent: \\(\\dfrac{a^{-2}b}{c^{-1}} = \\dfrac{bc}{a^2}\\).' },
    { title: 'The Golem\'s Fraction', lore: 'The obsidian golem was quarried from a single block and then split, and split again. Each split left a root. A root, the Ember Sprites sing, is just a power that has not made up its mind.',
      math: '<b>Rational exponents are roots.</b> \\(x^{\\frac{1}{n}} = \\sqrt[n]{x}\\), and \\(x^{\\frac{m}{n}} = \\left(\\sqrt[n]{x}\\right)^m = \\sqrt[n]{x^m}\\). Take the root first, it keeps the numbers small: \\(8^{\\frac{2}{3}} = \\left(\\sqrt[3]{8}\\right)^2 = 2^2 = 4\\); \\(16^{-\\frac{3}{4}} = \\dfrac{1}{\\left(\\sqrt[4]{16}\\right)^3} = \\dfrac{1}{8}\\). Going the other way: \\(\\sqrt[5]{x^2} = x^{\\frac{2}{5}}\\) and \\(\\sqrt{x^3} = x^{\\frac{3}{2}}\\).' },
    { title: 'Counting Ash', lore: 'When the Furnace King wakes, the ash of a thousand eruptions falls on the Peaks. Nobody can count the grains. The Pyroclast Drake does not count them; it writes how many zeros they would need.',
      math: '<b>Scientific notation</b>: \\(a \\times 10^n\\) with \\(1 \\le a < 10\\). Big numbers have a positive exponent, small ones negative: \\(4\\,250\\,000 = 4.25 \\times 10^6\\), \\(0.00031 = 3.1 \\times 10^{-4}\\). Count how many places the decimal point moves. To multiply, multiply the fronts and add the exponents: \\((3 \\times 10^4)(2 \\times 10^{-7}) = 6 \\times 10^{-3}\\). If the front leaves \\([1, 10)\\), fix it: \\(12 \\times 10^5 = 1.2 \\times 10^6\\).' },
    { title: 'The Unknown Scale', lore: 'The Ash Wyrm has one scale that does not match the others. It is the scale it hides. Find the law the rest obey and the hidden one has nowhere left to be.',
      math: '<b>Solving for a missing exponent</b>: write both sides with the same base, then set the exponents equal. \\(2^x \\cdot 2^3 = 2^{11} \\Rightarrow x + 3 = 11 \\Rightarrow x = 8\\). \\(\\dfrac{3^{x}}{3^{4}} = 3^{2} \\Rightarrow x = 6\\). \\(\\left(5^x\\right)^2 = 5^{10} \\Rightarrow 2x = 10\\). If the bases differ, rewrite them: \\(4^x = 2^{10} \\Rightarrow (2^2)^x = 2^{10} \\Rightarrow 2x = 10 \\Rightarrow x = 5\\).' }
  ],
  L3: [
    { title: 'Reading the Rings', lore: 'Cut a Weald tree and you can read it: every ring a term, the thickest ring its degree. The Thornling has three rings and dares you to name them. The Elder Treant has a thousand and will not stand still.',
      math: 'A <b>polynomial</b> is a sum of <b>terms</b>; each term is a number (the <b>coefficient</b>) times variables with whole-number exponents. The <b>degree</b> of a term is the sum of its exponents (\\(5x^2y^3\\) has degree 5); the degree of the polynomial is the largest term degree. Count terms for the name: 1 = monomial, 2 = binomial, 3 = trinomial. Write in <b>descending order</b> of degree: \\(3x^2 - 7x + 2\\).' },
    { title: 'What the Moss Keeps', lore: 'Moss remembers what the tree forgets. Put two fallen trunks side by side and the moss will tell you which rings they had in common and which they did not, and it never, ever drops a sign.',
      math: '<b>Adding and subtracting polynomials</b>: combine <b>like terms</b> (same variables, same exponents). Subtraction means subtracting <i>every</i> term in the second bracket, so flip all its signs first: \\((4x^2 - 3x + 1) - (x^2 - 5x - 6) = 4x^2 - 3x + 1 - x^2 + 5x + 6 = 3x^2 + 2x + 7\\). Line the terms up by degree and check that nothing was dropped.' },
    { title: 'The Weald Multiplies', lore: 'Say a thing once beneath the canopy and the Weald says it back from every branch. Say it to a single sprite and it reaches each of the sprite\'s wings in turn.',
      math: '<b>Distributing</b> a monomial: multiply it into <i>every</i> term, adding exponents on matching variables: \\(-2x^2(3x^2 - 4x + 5) = -6x^4 + 8x^3 - 10x^2\\). <b>Binomial × binomial</b> (FOIL: First, Outer, Inner, Last): \\((x + 3)(2x - 5) = 2x^2 - 5x + 6x - 15 = 2x^2 + x - 15\\). The middle terms are the ones people lose: there are always two of them before they combine.' },
    { title: 'The Shade\'s Cloak', lore: 'The Weald Shade squares itself in the dark and comes back with a cloak it did not have before, woven from the twice-counted middle. Look for the cloak; it is always there.',
      math: '<b>Special products</b> (learn these by heart): \\((a + b)^2 = a^2 + 2ab + b^2\\), \\((a - b)^2 = a^2 - 2ab + b^2\\), \\((a + b)(a - b) = a^2 - b^2\\). So \\((3x - 4)^2 = 9x^2 - 24x + 16\\), never \\(9x^2 + 16\\). And \\((2x + 5)(2x - 5) = 4x^2 - 25\\): the middle terms cancel. The cube: \\((x + a)^3 = x^3 + 3ax^2 + 3a^2x + a^3\\).' },
    { title: 'The Oak\'s Floor', lore: 'Under the Hollow Oak the roots have paved a floor in rectangles that are not rectangles, with corners cut away and gardens let in. Measure it by pieces, and multiply each piece out before you add.',
      math: '<b>Area and perimeter with polynomials</b>: perimeter adds all the sides (combine like terms); area multiplies length by width (expand). An L-shape or a cut-out is two rectangles: find each area and add or subtract. Example: a \\((2x + 3)\\) by \\((x + 4)\\) floor with an \\(x\\) by \\(x\\) square removed has area \\((2x + 3)(x + 4) - x^2 = 2x^2 + 11x + 12 - x^2 = x^2 + 11x + 12\\). Volume of a box: length × width × height, multiply two factors first, then the third.' }
  ],
  L4: [
    { title: 'Pulling the Bricks Apart', lore: 'Everything the Weald multiplied, the Crypts pull apart again. The scarabs begin at the mortar: whatever every brick has in common comes out first, and the wall remembers what is left.',
      math: '<b>Common factor first, always.</b> Find the GCF of the coefficients and the lowest power of each variable, then divide every term by it: \\(12x^3y - 18x^2y^2 = 6x^2y(2x - 3y)\\). Check by distributing back. Sometimes the common factor is a bracket: \\(x(x + 2) - 5(x + 2) = (x + 2)(x - 5)\\). That is also <b>factoring by grouping</b>: group four terms in pairs, factor each pair, then factor out the shared bracket.' },
    { title: 'The Two Numbers', lore: 'Each ghoul guards a door that opens to two numbers: the pair that multiply to the last and add to the middle. The ghoul remembers them. It is betting you will not.',
      math: '<b>\\(x^2 + bx + c\\)</b>: find two numbers that <b>multiply to \\(c\\)</b> and <b>add to \\(b\\)</b>. \\(x^2 + 7x + 12 = (x + 3)(x + 4)\\); \\(x^2 - 2x - 15 = (x - 5)(x + 3)\\) (product \\(-15\\) means opposite signs; sum \\(-2\\) means the bigger one is negative). List the factor pairs of \\(c\\) if you are stuck. If nothing works, the trinomial does not factor over the integers.' },
    { title: 'The Reliquary\'s Two Locks', lore: 'The Living Reliquary is a casket with a lock on the lid and a lock inside the lock. The difference between two squares opens the first. Most who open it stop there. Those who do not are the ones who leave.',
      math: '<b>Difference of squares</b>: \\(a^2 - b^2 = (a - b)(a + b)\\). Spot it: two terms, both perfect squares, a minus between. \\(9x^2 - 25 = (3x - 5)(3x + 5)\\); \\(x^4 - 16 = (x^2 - 4)(x^2 + 4) = (x - 2)(x + 2)(x^2 + 4)\\): keep factoring until nothing else will. A <i>sum</i> of squares, \\(x^2 + 9\\), does not factor. Common factor first: \\(2x^2 - 50 = 2(x^2 - 25) = 2(x - 5)(x + 5)\\).' },
    { title: 'The Knight\'s Decomposition', lore: 'The Crypt Knight\'s blade does not cut the middle term in half. It cuts it into two unequal pieces, chosen so that the whole falls into groups. The armour it wears is a perfect square; its blade was made for everything that is not.',
      math: '<b>\\(ax^2 + bx + c\\)</b> by <b>decomposition</b>: find two numbers that multiply to \\(a \\cdot c\\) and add to \\(b\\), split the middle term with them, then factor by grouping. \\(6x^2 + 7x - 3\\): \\(a c = -18\\), the pair is \\(9\\) and \\(-2\\). So \\(6x^2 + 9x - 2x - 3 = 3x(2x + 3) - 1(2x + 3) = (2x + 3)(3x - 1)\\). <b>Perfect-square trinomials</b>: \\(a^2 \\pm 2ab + b^2 = (a \\pm b)^2\\), e.g. \\(4x^2 - 12x + 9 = (2x - 3)^2\\). Check the middle: \\(2 \\cdot 2x \\cdot 3 = 12x\\).' },
    { title: 'Ossirion\'s Rule', lore: 'The Vaultkeeper allows one law in the Crypts: a thing that is nothing has at least one part that is nothing. Bring him a product that equals nothing and he must tell you which factor died.',
      math: '<b>Solving by factoring</b> uses the zero-product rule: if \\(A \\cdot B = 0\\) then \\(A = 0\\) or \\(B = 0\\). Get <b>everything on one side, zero on the other</b> first: \\(x^2 + 3x = 10 \\Rightarrow x^2 + 3x - 10 = 0 \\Rightarrow (x + 5)(x - 2) = 0 \\Rightarrow x = -5\\) or \\(x = 2\\). For \\((x + 1)(x + 4) = 10\\) you must expand and rearrange first; the factors are not zero. With a leading coefficient, \\(2x - 3 = 0\\) gives \\(x = \\tfrac{3}{2}\\). Always give every solution.' }
  ]
};
if (typeof module !== 'undefined') module.exports = LOREBOOK;
